### ISSUE TITLE
Issues with NILMTK converter

### ISSUE THREAD

**Issue by klemenjak** [ch-shin/enertalk-dataset-visualization#12]
Hi there,

thanks for sharing your code. I tried running that converter on the files obtained from figshare and ended up in multiple issues. Not sure why as I am sure to have followed all steps correctly.

Would you be so kind as to share the .h5 version of enertalk in some way?

best,
Christoph

**Comment by matheusthiago** [comment]
I'm having multiple issues with the GZIP files too and i'm not able to read these files yet.
Best regards

**Comment by matheusthiago** [comment]
For those that had some difficulties to read the ".gzip" files I indicate to use this code below: 

import pyarrow
import pandas as pd
base = "00_total.parquet.gzip" #here the dataset file 
data = pd.read_parquet(base)
data['timestamp'] = data['timestamp'].apply(lambda x: pd.Timestamp(x, unit='ms'))
data.head()

**Output**

**active_power	reactive_power	timestamp**
0	281.07	-215.83	2016-10-21 00:00:01.270
1	278.51	-216.43	2016-10-21 00:00:01.336
2	280.54	-216.56	2016-10-21 00:00:01.403
3	279.05	-215.97	2016-10-21 00:00:01.470
4	279.49	-215.78	2016-10-21 00:00:01.536

**Comment by klemenjak** [comment]
Thanks for sharing that code. It would be much more convenient if the authors share that enertalk.h5 file though.

**Comment by sastry3009** [comment]
I also need the file enertalk.h5 please share the file if any one have

**Comment by camilomarino** [comment]
I was able to get the converter working.

For this I had to install in my virtual environment:
- nilmtk
- nilm_metadata
- pyarrow
- tqdm

It's also important to download the data for all 22 houses from: https://springernature.figshare.com/collections/The_ENERTALK_Dataset_15_Hz_Electricity_Consumption_Data_from_22_Houses_in_Korea/4502780 (it's at the bottom)
Then I unzipped each of the folders into the same folder, it should look like this:
./data
 ├── 00
 ├── 01
  .
  .
 ├── 20
 └── 21
It is important that the data for ALL houses is present, otherwise you will get the error "AttributeError: Object 'NoneType' does not have attribute '_v_attrs'".

Then add two lines to the “meter_devices.yaml” file, as in pull request #35 , you can see it at https://github.com/ch-shin/ENERTALK-dataset/pull/35/files#diff-a3430607b9d18e65f8a0e04e8bcd82ab99219a13df9b5b1804b01b4f6f2c3b20. If you don't do this, some nilmtk methods won't work.

Lastly, run the converter they implemented.

This took a long time, I think like 15 hours, and the generated ".h5" is about 200 Gb big. If the "h5" wasn't so big, I'd have no problem making it available.

**Comment by sastry3009** [comment]
thank you for your reply sir

I followed the steps which you mentioned in the mail still i got the error
as follows
Traceback (most recent call last):
  File "convert_enertalk.py", line 115, in <module>
    convert_enertalk(input_path, output_filename)
  File "convert_enertalk.py", line 42, in convert_enertalk

save_yaml_to_datastore('/home/sastry/Desktop/ENERTALK-dataset/nilmtk-converter/enertalk_metadata',
store)
  File
"/home/sastry/anaconda3/envs/nilm3/lib/python3.6/site-packages/nilm_metadata/convert_yaml_to_hdf5.py",
line 96, in save_yaml_to_datastore
    store.save_metadata('/'+building, building_metadata)
  File
"/home/sastry/anaconda3/envs/nilm3/lib/python3.6/site-packages/nilmtk/docinherit.py",
line 53, in f
    return self.mthd(obj, *args, **kwargs)
  File
"/home/sastry/anaconda3/envs/nilm3/lib/python3.6/site-packages/nilmtk/datastore/hdfdatastore.py",
line 196, in save_metadata
    node._v_attrs.metadata = metadata
AttributeError: 'NoneType' object has no attribute '_v_attrs'
Closing remaining open
files:/tmp/nilmtk-uku_38n7.h5...done/home/sastry/Desktop/enertalk_converted/enertalk.h5...done
(nilm3) ***@***.***:~/Desktop

**Comment by camilomarino** [comment]
That error has already happened to me with other datasets. As I mentioned before, I think that happens when there are more metadata files in the metadata (https://github.com/ch-shin/ENERTALK-dataset/tree/master/nilmtk-converter/metadata) folder than converted files.
In other words, it happened to me when I didn't download all the data and the conversion script tries to add metadata for the data that wasn't downloaded (and thus not added to the h5).

Are you sure you have downloaded all the data and put it in the folder structure I mentioned? What is the size of the generated h5 file?

**Comment by sastry3009** [comment]
Sorry for the late reply sir @camilomarino  As you told I downloaded the complete dataset and convert it to h5. I finally got the h5 file of size (140GB) sir 

Thanking you for your help 

Now again while running the algorithms i got an error regarding max_sample_period sir. The error is as follows

========== OPEN DATASETS ============
2022-03-16 10:24:55.838207: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
========== TRAIN ============
Traceback (most recent call last):
  File "/content/drive/MyDrive/neural-disaggregator/TCN/enertalk-test.py", line 32, in <module>
    tcn.train(train_mains, train_meter, epochs=1, sample_period=1)
  File "/content/drive/MyDrive/neural-disaggregator/TCN/tcndisaggregator.py", line 69, in train
    mainchunk = next(main_power_series)
  File "/usr/local/lib/python3.7/dist-packages/nilmtk/electric.py", line 625, in load_series
    generator = self.load(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nilmtk/elecmeter.py", line 436, in load
    np.ceil(self.device['max_sample_period'] / sample_period))
KeyError: 'max_sample_period'


could any one help me in rectifying this error
Thanking you

**Comment by camilomarino** [comment]
Did you add two lines to the "meter_devices.yaml" file, like in pull request #35? You can see the two lines at: https://github.com/ch-shin/ENERTALK-dataset/pull/35/files#diff-a3430607b9d18e65f8a0e04e8bcd82ab99219a13df9b5b1804b01b4f6f2c3b20 ?
That addition is because NILMTK needs `max_sample_period` for some of its functions.
